# Generated by Django 5.2.13 on 2026-04-08 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Баллы за вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('test', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Пусто — без ограничения. При истечении сохраняются уже данные ответы.', null=True, verbose_name='Лимит времени (сек)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Стандартные группы Django = отделы. Пусто — тест доступен любому авторизованному пользователю.', related_name='allowed_tests', to='auth.group', verbose_name='Отделы с доступом')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён'), ('timed_out', 'Истекло время'), ('abandoned', 'Прерван')], db_index=True, default='in_progress', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Рассчитывается при старте, если у теста задан лимит времени.', null=True, verbose_name='Дедлайн')),
                ('score_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Набрано баллов')),
                ('score_max', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимум баллов (на момент расчёта)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='testing.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AttemptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Отвечено')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.answeroption', verbose_name='Выбранный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Вопрос')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testing.testattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ в попытке',
                'verbose_name_plural': 'Ответы в попытке',
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['-started_at'], name='testing_tes_started_e39101_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test'], name='testing_tes_user_id_5cefca_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question_response'),
        ),
    ]
