# Generated by Django 5.2.13 on 2026-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='conduct_ends_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — без ограничения по окончанию. После этой даты тест недоступен; при сохранении флаг «Активен» снимается.', null=True, verbose_name='Окончание проведения'),
        ),
        migrations.AddField(
            model_name='test',
            name='conduct_starts_at',
            field=models.DateTimeField(blank=True, help_text='Пусто — без ограничения с начала. До этой даты тест для сдающих недоступен.', null=True, verbose_name='Начало проведения'),
        ),
    ]
