# Generated by Django 5.2.13 on 2026-04-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_seed_department_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=20, verbose_name='Тип действия')),
                ('model_name', models.CharField(db_index=True, max_length=120, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Изменённые поля')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Лог действий админа',
                'verbose_name_plural': 'Логи действий админа',
                'ordering': ('-created_at',),
            },
        ),
    ]
