# Generated by Django 5.2.13 on 2026-04-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_attempt_session_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attemptsessionevent',
            new_name='testing_att_attempt_ee579b_idx',
            old_name='testing_att_attempt_e2cbf5_idx',
        ),
        migrations.RenameIndex(
            model_name='attemptsessionevent',
            new_name='testing_att_user_id_e27815_idx',
            old_name='testing_att_user_id_7e8f1a_idx',
        ),
    ]
