# Generated by Django 5.2.13 on 2026-04-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testing', '0017_testattempt_termination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactionlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Admin harakatlari jurnali', 'verbose_name_plural': 'Admin harakatlari jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='attemptresponse',
            options={'verbose_name': 'Urinishdagi javob', 'verbose_name_plural': 'Urinishdagi javoblar'},
        ),
        migrations.AlterModelOptions(
            name='attemptsessionevent',
            options={'ordering': ('created_at',), 'verbose_name': 'Urinish sessiyasi hodisasi', 'verbose_name_plural': 'Urinish sessiyalari hodisalari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('test', 'order', 'id'), 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'ordering': ('-started_at',), 'verbose_name': 'Urinish', 'verbose_name_plural': 'Urinishlar'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi profili', 'verbose_name_plural': 'Foydalanuvchilar profillari'},
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Yaratish'), ('update', "O'zgartirish"), ('delete', "O'chirish")], max_length=20, verbose_name='Harakat turi'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kim bajardi'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list, verbose_name="O'zgartirilgan maydonlar"),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-manzil'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Obyekt'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='attemptresponse',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan'),
        ),
        migrations.AlterField(
            model_name='attemptresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='testing.testattempt', verbose_name='Urinish'),
        ),
        migrations.AlterField(
            model_name='attemptresponse',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri"),
        ),
        migrations.AlterField(
            model_name='attemptresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='attemptresponse',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.answeroption', verbose_name='Tanlangan variant'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_events', to='testing.testattempt', verbose_name='Urinish'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, help_text="Brauzerdan ISO vaqti, agar uzatilgan bo'lsa.", null=True, verbose_name='Mijoz vaqti'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Serverda qayd etilgan'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='duration_away_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Odatda page_visible da: sahifa necha ms yashiringan edi.', null=True, verbose_name='Sahifadan tashqari davomiyligi, ms'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='event_type',
            field=models.CharField(choices=[('page_hidden', 'Sahifa yashirildi (visibility)'), ('page_visible', "Sahifa yana ko'rinmoqda"), ('window_blur', "Oyna fokusni yo'qotdi"), ('window_focus', 'Oyna fokusni oldi')], db_index=True, max_length=32, verbose_name='Hodisa turi'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='leave_count',
            field=models.PositiveIntegerField(blank=True, help_text="To'planma ketish raqami, agar front hisoblagichni boshqarsa.", null=True, verbose_name='Ketish hisoblagichi (mijozdan)'),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='attemptsessionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_session_events', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Savol uchun ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='test',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text="Django standart guruhlari = bo'limlar. Bo'sh — test har qanday autentifikatsiya qilingan foydalanuvchiga mavjud.", related_name='allowed_tests', to='auth.group', verbose_name="Kirish huquqi bo'limlar"),
        ),
        migrations.AlterField(
            model_name='test',
            name='conduct_ends_at',
            field=models.DateTimeField(blank=True, help_text="Bo'sh — tugashida cheklovsiz. Bu sanadan keyin test mavjud emas; saqlashda «Faol» belgisi olib tashlanadi.", null=True, verbose_name="O'tkazish tugashi"),
        ),
        migrations.AlterField(
            model_name='test',
            name='conduct_starts_at',
            field=models.DateTimeField(blank=True, help_text="Bo'sh — boshidan cheklovsiz. Bu sanagacha test topshiruvchilarga mavjud emas.", null=True, verbose_name="O'tkazish boshlanishi"),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Bo'sh — cheklovsiz. Vaqt tugaganda mavjud javoblar saqlanadi.", null=True, verbose_name='Vaqt chegarasi (sek)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text="Testda vaqt chegarasi belgilangan bo'lsa, startda hisoblanadi.", null=True, verbose_name='Muddat'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='question_sequence',
            field=models.JSONField(blank=True, help_text='Urinish boshida tasodifiy tartib; next_question va muvofiq tartib uchun.', null=True, verbose_name='Savollar tartibi (id)'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="To'plangan ball"),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maksimal ball (hisoblash vaqtida)'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Boshlanish'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('timed_out', 'Vaqt tugadi'), ('abandoned', "To'xtatilgan"), ('terminated', 'Majburan tugatildi')], db_index=True, default='in_progress', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='testing.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region_type',
            field=models.CharField(choices=[('markaziy', 'Markaziy apparat'), ('viloyat', 'Viloyat')], default='markaziy', max_length=20, verbose_name='Hudud turi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='viloyat',
            field=models.CharField(blank=True, choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('fargona', "Farg'ona viloyati"), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('toshkent_vil', 'Toshkent viloyati'), ('xorazm', 'Xorazm viloyati'), ('toshkent_sh', 'Toshkent shahri'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('questions_to_show', models.PositiveSmallIntegerField(blank=True, help_text="Bo'sh — barcha savollar. Har bir urinishda tasodifiy tanlanadi.", null=True, verbose_name="Ko'rsatiladigan savollar soni")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_groups', to='auth.group', verbose_name="Bo'lim")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='testing.test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol guruhi',
                'verbose_name_plural': 'Savol guruhlari',
                'ordering': ('test', 'order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.questiongroup', verbose_name='Savol guruhi'),
        ),
    ]
