# Generated by Django 5.2.13 on 2026-04-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_question_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='title',
        ),
    ]
